name = "team-dream-app"
compatibility_date = "2026-06-02"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "team-dream-sessions"
database_id = "19850d66-750d-4123-a5db-9dd480931c0e"
